import type { Metadata } from "next";
import ThemeMain from "./components/themeMain";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeMain>{children}</ThemeMain>
    </html>
  );
}
